package sqlm

import (
	"reflect"

	"github.com/qjebbs/go-sqlb"
	"github.com/qjebbs/go-sqlb/dialect"
	"github.com/qjebbs/go-sqlf/v4"
	"github.com/qjebbs/go-sqlm/option"
	"github.com/qjebbs/go-sqlm/tag"
)

// selectable is the interface that a model struct should implement to be used in Select with struct mapping.
// It's unexported and not implemented by users directly, but generated by codegen tools.
type selectable[T any] interface {
	// New creates and returns a new instance of the model struct. It's used to create new instances for scanning query results into.
	New() T
	// Tags returns the tags of the model fields in the same order as Fields().
	Tags() []*tag.Info
	// Fields returns a slice of pointers to the fields of the model in the same order as Tags().
	// The fields must be pointers, so that they can be scanned into.
	Fields() []any
	// FillFields fills the target slice with the field pointers corresponding to the given indexes.
	// The indexes are the positions of the selected fields in the Tags() slice, which are determined by the struct tags and selection options.
	// This method is used to fill the scan destinations for sql.Rows.Scan() based on the selected fields.
	FillFields(target []any, indexes []int)
}

func _selectSelectable[T any](ctx sqlb.Context, db Querier, b SelectBuilder, model selectable[T], options ...option.Option) ([]T, error) {
	opt := option.New(options...)
	var debugger *debugger
	if opt.Debug.Enabled {
		debugger = newDebugger("Select", model, opt)
		defer debugger.print(ctx.BaseDialect())
	}
	queryStr, args, indexes, err := buildSelectQueryForModel(ctx, ctx.Dialect(), b, model, opt)
	if err != nil {
		return nil, err
	}
	if debugger != nil {
		debugger.onBuilt(queryStr, args)
	}
	if db == nil {
		return nil, ErrNilDB
	}
	return scanQuery(ctx, db, queryStr, args, debugger, func() (T, []any) {
		m := model.New()
		values := make([]any, len(indexes))
		// Prepare the slice of destinations for sql.Rows.Scan().
		//
		// PERFORMANCE-CRITICAL:
		// The `FillValues` method is intentionally designed not to return a slice. Instead,
		// we pre-allocate the `values` slice here and pass it in to be filled.
		//
		// This design is crucial for escape analysis. When a function returns a slice (or any pointer type),
		// the compiler must assume it will be used beyond the function's scope and allocates it on the heap.
		// By creating the slice here and using it only within this factory function, we signal to the
		// compiler that the slice's lifetime is confined. This gives the compiler the opportunity
		// to perform an optimization and allocate the `values` slice on the stack instead of the heap,
		// effectively making this part of the scan preparation a zero-allocation operation.
		any(m).(selectable[T]).FillFields(values, indexes)
		return m, values
	})
}

func buildSelectQueryForModel[T any](ctx sqlb.Context, d dialect.Dialect, b SelectBuilder, model selectable[T], opt *option.Options) (query string, args []any, dests []int, err error) {
	if opt == nil {
		opt = option.New()
	}

	tags := model.Tags()
	values := model.Fields()
	dests = make([]int, 0, len(tags))
	var columns []sqlf.Builder
	for i, tag := range tags {
		if tag.Column == "" && tag.Select == "" {
			continue
		}
		if len(tag.SelectOn) > 0 && !opt.Select.Tags.ContainsAny(tag.SelectOn) {
			continue
		}
		dests = append(dests, i)
		column, err := buildSelectColumn(d, tag, reflect.TypeOf(values[i]).Elem(), opt)
		if err != nil {
			return "", nil, nil, err
		}
		columns = append(columns, column)
	}
	b.SetSelect(columns...)
	query, args, err = sqlf.Build(ctx, b)
	if err != nil {
		return "", nil, nil, err
	}
	return query, args, dests, nil
}
